name: Run a Dynamic Application Security Testing

on:
  push:
    branches: [ "master" ] 

  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        id: checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
      - name: ZAP Scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.VCS_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: Posting Action Workflow updates to Slack
        id: slack notification
        uses: act10ns/slack@v2
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-actions'
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
